### ISSUE TITLE
Percent Button

### ISSUE THREAD

**Issue by Craig-Codes** [ElvisMac/calculator#14]
Once percent has been pressed, typing numbers carries on adding to number to the screen. 

Numbers should start again once percentage has been pressed, not carry on adding to the current display amount.

**Comment by ElvisMac** [comment]
Fixed by adding a catch all for the total variable inside the calculator class.  If the total is a blank string, undefined, or contains zero, it sets the reset flag to true.  Then in build number it updates the current variable to a blank string, updates the display and sets the percent reset flag back to false.
